name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/upload-keystore.jks

      - name: Create key.properties
        run: |
          cat > android/key.properties <<EOF
          storePassword=${{ secrets.STORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=upload-keystore.jks
          EOF

      - run: flutter pub get

      - name: Verify signing files
        run: |
          echo "===== android directory ====="
          ls -la android

          echo "===== key.properties ====="
          cat android/key.properties

          echo "===== keystore info ====="
          file android/upload-keystore.jks
          wc -c android/upload-keystore.jks

      - run: flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: BookVerse-APK
          path: build/app/outputs/flutter-apk/app-release.apk